### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by intersoftsistemas** [AkshayGadekar/React-MUI-Dashboard-with-JavaScript#1]
Access to XMLHttpRequest at 'https://callqx-portal.ecosmob.net/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by AkshayGadekar** [comment]
hi @intersoftsistemas , I apologize for the late response. You are not able to login because API server is shut down now, so to fix it static responses are shown in code. So now you can login, know that data shown inside is dummy data. You can understand functionality from code, which is the main purpose of this repo.
